name: Build Linux
on: [push, pull_request]

jobs:
  build:
    name: MOM6cmake
    runs-on: ubuntu-latest
    env:
      CC: gcc-7
      FC: gfortran-7
      VERBOSE: 1

    steps:

    - name: install-netcdf
      run: |
        sudo apt-get install libnetcdf-dev libnetcdff-dev netcdf-bin pkg-config

    - name: install-mpi
      run: |
        sudo apt-get install libmpich-dev

    - name: checkout-mom6-tools
      uses: actions/checkout@v2
      with:
        path: mom6-tools
        submodules: true

    - name: build-mom6-tools
      run: |
        cd mom6-tools/MOM6-cmake
        mkdir build
        cd build
        export NetCDF_ROOT=$(nc-config --prefix)
        cmake -DOPENMP=OFF -DCMAKE_INSTALL_PREFIX=../install ..
        make -j4
